/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadora.proyecto.pkg1.pkg0;

import java.awt.Color;

/**
 *
 * @author 20PROGB18
 */
public class frmPrincipal extends javax.swing.JFrame {

    private double valor1 = 0;
    private String operacion = null ;
    
    
    public frmPrincipal() {
        initComponents();
        this.getContentPane().setBackground(Color.pink);
    }
    public int factorial (int numero){
        if (numero == 0){
            return 1;   
        }else {
            return numero *factorial (numero-1);
        }
        
      
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtPantalla = new javax.swing.JTextArea();
        btnMas = new javax.swing.JButton();
        btnX2 = new javax.swing.JButton();
        btnSeno = new javax.swing.JButton();
        btnIn = new javax.swing.JButton();
        btnNueve = new javax.swing.JButton();
        btnTres = new javax.swing.JButton();
        btnSeis = new javax.swing.JButton();
        btnMenos = new javax.swing.JButton();
        btnXy = new javax.swing.JButton();
        btnCoseno = new javax.swing.JButton();
        btnLog = new javax.swing.JButton();
        btnOcho = new javax.swing.JButton();
        btnDos = new javax.swing.JButton();
        btnCinco = new javax.swing.JButton();
        btnMultiplicacion = new javax.swing.JButton();
        btnsignoX = new javax.swing.JButton();
        btnTangente = new javax.swing.JButton();
        btnSiete = new javax.swing.JButton();
        btnUno = new javax.swing.JButton();
        btnCuatro = new javax.swing.JButton();
        btnPunto = new javax.swing.JButton();
        btnX = new javax.swing.JButton();
        btnC = new javax.swing.JButton();
        btnDivicion = new javax.swing.JButton();
        jButtonResultados = new javax.swing.JButton();
        btnCero = new javax.swing.JButton();
        btnPorcentaje = new javax.swing.JButton();
        btnraizcuadrada = new javax.swing.JButton();
        btnCe = new javax.swing.JButton();
        btnAutor = new javax.swing.JButton();
        rbBinario = new javax.swing.JRadioButton();
        rbHexadecimal = new javax.swing.JRadioButton();
        rbOctal = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtPantalla.setBackground(new java.awt.Color(255, 204, 204));
        txtPantalla.setColumns(20);
        txtPantalla.setRows(2);
        jScrollPane1.setViewportView(txtPantalla);

        btnMas.setBackground(new java.awt.Color(206, 109, 109));
        btnMas.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        btnMas.setText("+");
        btnMas.setPreferredSize(new java.awt.Dimension(40, 50));
        btnMas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMasActionPerformed(evt);
            }
        });

        btnX2.setBackground(new java.awt.Color(206, 109, 109));
        btnX2.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        btnX2.setText("x^2");
        btnX2.setPreferredSize(new java.awt.Dimension(40, 50));
        btnX2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnX2ActionPerformed(evt);
            }
        });

        btnSeno.setBackground(new java.awt.Color(206, 109, 109));
        btnSeno.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        btnSeno.setText("SEN");
        btnSeno.setPreferredSize(new java.awt.Dimension(40, 50));
        btnSeno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSenoActionPerformed(evt);
            }
        });

        btnIn.setBackground(new java.awt.Color(206, 109, 109));
        btnIn.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        btnIn.setText("Ln");
        btnIn.setPreferredSize(new java.awt.Dimension(40, 50));
        btnIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInActionPerformed(evt);
            }
        });

        btnNueve.setBackground(new java.awt.Color(206, 109, 109));
        btnNueve.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        btnNueve.setText("9");
        btnNueve.setPreferredSize(new java.awt.Dimension(40, 50));
        btnNueve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNueveActionPerformed(evt);
            }
        });

        btnTres.setBackground(new java.awt.Color(206, 109, 109));
        btnTres.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        btnTres.setText("3");
        btnTres.setPreferredSize(new java.awt.Dimension(40, 50));
        btnTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTresActionPerformed(evt);
            }
        });

        btnSeis.setBackground(new java.awt.Color(206, 109, 109));
        btnSeis.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        btnSeis.setText("6");
        btnSeis.setPreferredSize(new java.awt.Dimension(40, 50));
        btnSeis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeisActionPerformed(evt);
            }
        });

        btnMenos.setBackground(new java.awt.Color(206, 109, 109));
        btnMenos.setFont(new java.awt.Font("Tahoma", 2, 36)); // NOI18N
        btnMenos.setText("-");
        btnMenos.setPreferredSize(new java.awt.Dimension(40, 50));
        btnMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenosActionPerformed(evt);
            }
        });

        btnXy.setBackground(new java.awt.Color(206, 109, 109));
        btnXy.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        btnXy.setText("x^y");
        btnXy.setPreferredSize(new java.awt.Dimension(40, 50));
        btnXy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXyActionPerformed(evt);
            }
        });

        btnCoseno.setBackground(new java.awt.Color(206, 109, 109));
        btnCoseno.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        btnCoseno.setText("COS");
        btnCoseno.setPreferredSize(new java.awt.Dimension(40, 50));
        btnCoseno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCosenoActionPerformed(evt);
            }
        });

        btnLog.setBackground(new java.awt.Color(206, 109, 109));
        btnLog.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        btnLog.setText("Log");
        btnLog.setPreferredSize(new java.awt.Dimension(40, 50));
        btnLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogActionPerformed(evt);
            }
        });

        btnOcho.setBackground(new java.awt.Color(206, 109, 109));
        btnOcho.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        btnOcho.setText("8");
        btnOcho.setPreferredSize(new java.awt.Dimension(40, 50));
        btnOcho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOchoActionPerformed(evt);
            }
        });

        btnDos.setBackground(new java.awt.Color(206, 109, 109));
        btnDos.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        btnDos.setText("2");
        btnDos.setPreferredSize(new java.awt.Dimension(40, 50));
        btnDos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDosActionPerformed(evt);
            }
        });

        btnCinco.setBackground(new java.awt.Color(206, 109, 109));
        btnCinco.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        btnCinco.setText("5");
        btnCinco.setPreferredSize(new java.awt.Dimension(40, 50));
        btnCinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCincoActionPerformed(evt);
            }
        });

        btnMultiplicacion.setBackground(new java.awt.Color(206, 109, 109));
        btnMultiplicacion.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        btnMultiplicacion.setText("x");
        btnMultiplicacion.setPreferredSize(new java.awt.Dimension(40, 50));
        btnMultiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplicacionActionPerformed(evt);
            }
        });

        btnsignoX.setBackground(new java.awt.Color(206, 109, 109));
        btnsignoX.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        btnsignoX.setText("1 / x");
        btnsignoX.setPreferredSize(new java.awt.Dimension(40, 50));
        btnsignoX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsignoXActionPerformed(evt);
            }
        });

        btnTangente.setBackground(new java.awt.Color(206, 109, 109));
        btnTangente.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        btnTangente.setText("TAN");
        btnTangente.setPreferredSize(new java.awt.Dimension(40, 50));
        btnTangente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTangenteActionPerformed(evt);
            }
        });

        btnSiete.setBackground(new java.awt.Color(206, 109, 109));
        btnSiete.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        btnSiete.setText("7");
        btnSiete.setPreferredSize(new java.awt.Dimension(40, 50));
        btnSiete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSieteActionPerformed(evt);
            }
        });

        btnUno.setBackground(new java.awt.Color(206, 109, 109));
        btnUno.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        btnUno.setText("1");
        btnUno.setPreferredSize(new java.awt.Dimension(40, 50));
        btnUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnoActionPerformed(evt);
            }
        });

        btnCuatro.setBackground(new java.awt.Color(206, 109, 109));
        btnCuatro.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        btnCuatro.setText("4");
        btnCuatro.setPreferredSize(new java.awt.Dimension(40, 50));
        btnCuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCuatroActionPerformed(evt);
            }
        });

        btnPunto.setBackground(new java.awt.Color(206, 109, 109));
        btnPunto.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        btnPunto.setText(".");
        btnPunto.setPreferredSize(new java.awt.Dimension(40, 50));
        btnPunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPuntoActionPerformed(evt);
            }
        });

        btnX.setBackground(new java.awt.Color(206, 109, 109));
        btnX.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        btnX.setText("x !");
        btnX.setPreferredSize(new java.awt.Dimension(40, 50));
        btnX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXActionPerformed(evt);
            }
        });

        btnC.setBackground(new java.awt.Color(206, 109, 109));
        btnC.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        btnC.setText("C");
        btnC.setPreferredSize(new java.awt.Dimension(40, 50));
        btnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCActionPerformed(evt);
            }
        });

        btnDivicion.setBackground(new java.awt.Color(206, 109, 109));
        btnDivicion.setFont(new java.awt.Font("Tahoma", 2, 8)); // NOI18N
        btnDivicion.setText("/");
        btnDivicion.setPreferredSize(new java.awt.Dimension(40, 50));
        btnDivicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivicionActionPerformed(evt);
            }
        });

        jButtonResultados.setBackground(new java.awt.Color(206, 109, 109));
        jButtonResultados.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jButtonResultados.setText("=");
        jButtonResultados.setPreferredSize(new java.awt.Dimension(40, 50));
        jButtonResultados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResultadosActionPerformed(evt);
            }
        });

        btnCero.setBackground(new java.awt.Color(206, 109, 109));
        btnCero.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        btnCero.setText("0");
        btnCero.setPreferredSize(new java.awt.Dimension(40, 50));
        btnCero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCeroActionPerformed(evt);
            }
        });

        btnPorcentaje.setBackground(new java.awt.Color(206, 109, 109));
        btnPorcentaje.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        btnPorcentaje.setText("%");
        btnPorcentaje.setPreferredSize(new java.awt.Dimension(40, 50));
        btnPorcentaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPorcentajeActionPerformed(evt);
            }
        });

        btnraizcuadrada.setBackground(new java.awt.Color(206, 109, 109));
        btnraizcuadrada.setFont(new java.awt.Font("Tahoma", 2, 8)); // NOI18N
        btnraizcuadrada.setPreferredSize(new java.awt.Dimension(40, 50));
        btnraizcuadrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnraizcuadradaActionPerformed(evt);
            }
        });

        btnCe.setBackground(new java.awt.Color(206, 109, 109));
        btnCe.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        btnCe.setText("CE");
        btnCe.setPreferredSize(new java.awt.Dimension(40, 50));
        btnCe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCeActionPerformed(evt);
            }
        });

        btnAutor.setBackground(new java.awt.Color(206, 109, 109));
        btnAutor.setFont(new java.awt.Font("Tahoma", 2, 8)); // NOI18N
        btnAutor.setText("AUTOR");
        btnAutor.setPreferredSize(new java.awt.Dimension(40, 50));
        btnAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAutorActionPerformed(evt);
            }
        });

        rbBinario.setBackground(new java.awt.Color(206, 109, 109));
        rbBinario.setFont(new java.awt.Font("Tahoma", 2, 8)); // NOI18N
        rbBinario.setText("A Binario");
        rbBinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbBinarioActionPerformed(evt);
            }
        });

        rbHexadecimal.setBackground(new java.awt.Color(206, 109, 109));
        rbHexadecimal.setFont(new java.awt.Font("Tahoma", 2, 5)); // NOI18N
        rbHexadecimal.setText("A Hexadecimal");
        rbHexadecimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbHexadecimalActionPerformed(evt);
            }
        });

        rbOctal.setBackground(new java.awt.Color(206, 109, 109));
        rbOctal.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        rbOctal.setText("A Octal");
        rbOctal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbOctalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnTres, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnDos, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnUno, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonResultados, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSeis, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnCinco, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnCuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnCero, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnX2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnMas, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnNueve, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnIn, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnSeno, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnXy, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnCoseno, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnOcho, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnLog, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnsignoX, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnMultiplicacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnTangente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnSiete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rbBinario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnPunto, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnDivicion, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btnX, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(rbHexadecimal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnraizcuadrada, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnPorcentaje, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnCe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnAutor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rbOctal, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(18, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(btnX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnCoseno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnSeno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(btnTangente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnX2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnMas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnNueve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(btnLog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnXy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnMenos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnOcho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnSiete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rbBinario, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rbHexadecimal, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnsignoX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnMultiplicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(btnDivicion, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(4, 4, 4)
                                .addComponent(btnPunto, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(rbOctal, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(btnraizcuadrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPorcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCuatro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnSeis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCinco, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnCero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnTres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnDos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonResultados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(104, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnraizcuadradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnraizcuadradaActionPerformed
        double n = Double.parseDouble(txtPantalla.getText());
        txtPantalla.setText(String.valueOf(Math.sqrt(n)));
    }//GEN-LAST:event_btnraizcuadradaActionPerformed

    private void btnCosenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCosenoActionPerformed
double n = Double.parseDouble(txtPantalla.getText());
        double x = Math.toRadians(n);
       txtPantalla.setText(String.valueOf(Math.cos(x)));        // TODO add your handling code here:
    }//GEN-LAST:event_btnCosenoActionPerformed

    private void btnSenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSenoActionPerformed
        double n = Double.parseDouble(txtPantalla.getText());
        double x = Math.toRadians(n);
        txtPantalla.setText(String.valueOf(Math.sin(x)));
    }//GEN-LAST:event_btnSenoActionPerformed

    private void btnTangenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTangenteActionPerformed
        double n = Double.parseDouble(txtPantalla.getText());
        double x = Math.toRadians(n);
        txtPantalla.setText(String.valueOf(Math.tan(x)));
        
    }//GEN-LAST:event_btnTangenteActionPerformed

    private void btnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCActionPerformed
       txtPantalla.setText("");
    }//GEN-LAST:event_btnCActionPerformed

    private void btnUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnoActionPerformed
         txtPantalla.append("1");
    }//GEN-LAST:event_btnUnoActionPerformed

    private void btnDosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDosActionPerformed
        txtPantalla.append("2");
    }//GEN-LAST:event_btnDosActionPerformed

    private void btnTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTresActionPerformed
        txtPantalla.append("3");
    }//GEN-LAST:event_btnTresActionPerformed

    private void btnCuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCuatroActionPerformed
        txtPantalla.append("4");
    }//GEN-LAST:event_btnCuatroActionPerformed

    private void btnCincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCincoActionPerformed
        txtPantalla.append("5");
    }//GEN-LAST:event_btnCincoActionPerformed

    private void btnSeisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeisActionPerformed
        txtPantalla.append("6");
    }//GEN-LAST:event_btnSeisActionPerformed

    private void btnSieteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSieteActionPerformed
        txtPantalla.append("7");
    }//GEN-LAST:event_btnSieteActionPerformed

    private void btnOchoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOchoActionPerformed
        txtPantalla.append("8");
    }//GEN-LAST:event_btnOchoActionPerformed

    private void btnNueveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNueveActionPerformed
        txtPantalla.append("9");
    }//GEN-LAST:event_btnNueveActionPerformed

    private void btnCeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCeroActionPerformed
       txtPantalla.append("0");
    }//GEN-LAST:event_btnCeroActionPerformed

    private void btnCeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCeActionPerformed
        String valor = txtPantalla.getText();
        txtPantalla.setText(valor.substring(0, valor.length()-1));
    }//GEN-LAST:event_btnCeActionPerformed

    private void btnLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogActionPerformed
        double valor,log;
        valor=Double.parseDouble(txtPantalla.getText());
        log=Math.log10(valor);
        txtPantalla.setText (String.valueOf(log));
    }//GEN-LAST:event_btnLogActionPerformed

    private void btnInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInActionPerformed
        double valor = Double.parseDouble(txtPantalla.getText ());
        double log = Math.log(valor);
        txtPantalla.setText(String.valueOf(log));
    }//GEN-LAST:event_btnInActionPerformed

    private void btnsignoXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsignoXActionPerformed
        double n = Double.parseDouble(txtPantalla.getText());
        n = 1 / n;
        txtPantalla.setText(String.valueOf(n*n));
    }//GEN-LAST:event_btnsignoXActionPerformed

    private void btnAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAutorActionPerformed
        frmAutor frm = new frmAutor();
        frm.setVisible(true);
    }//GEN-LAST:event_btnAutorActionPerformed

    private void btnX2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnX2ActionPerformed
       double n = Double.parseDouble(txtPantalla.getText());
      txtPantalla.setText(String.valueOf(n*n));
    }//GEN-LAST:event_btnX2ActionPerformed

    private void btnXyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXyActionPerformed
        valor1 =Double.parseDouble(txtPantalla.getText());
        txtPantalla.setText("");
        operacion = "potenciacirXY";
    }//GEN-LAST:event_btnXyActionPerformed

    private void jButtonResultadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResultadosActionPerformed
        double valor2 = Double.parseDouble(txtPantalla.getText());
        
        switch (operacion){
            case "suma":
                txtPantalla.setText(String.valueOf(valor1+valor2));
                break;
            case "resta":
                txtPantalla.setText(String.valueOf(valor1-valor2));
                break;
            case "multiplicacion":
                txtPantalla.setText(String.valueOf(valor1*valor2));
                break;
            case "divicion":
                if (valor2==0){
                    txtPantalla.setText("ERROR");  
                }
                else{
                    txtPantalla.setText(String.valueOf(valor1/valor2));
                }
            break;
            case "porcentaje":
                txtPantalla.setText(String.valueOf(valor1*valor2));
                break;
            case "potenciarXY":
                txtPantalla.setText(String.valueOf(Math.pow(valor1,valor2)));
                break;
            default:
                break;
        }
    }//GEN-LAST:event_jButtonResultadosActionPerformed
           
    private void btnXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXActionPerformed
            txtPantalla.setText(String.valueOf(factorial(Integer.parseInt(txtPantalla.getText()))));        
    }//GEN-LAST:event_btnXActionPerformed

    private void btnMasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMasActionPerformed
        valor1=Double.parseDouble(txtPantalla.getText());
        txtPantalla.setText("");
        operacion="suma";
    }//GEN-LAST:event_btnMasActionPerformed

    private void btnMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenosActionPerformed
        valor1=Double.parseDouble(txtPantalla.getText());
        txtPantalla.setText("");
        operacion="resta";
    }//GEN-LAST:event_btnMenosActionPerformed

    private void btnMultiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplicacionActionPerformed
        valor1=Double.parseDouble(txtPantalla.getText());
        txtPantalla.setText("");
        operacion="multiplicacion";
    }//GEN-LAST:event_btnMultiplicacionActionPerformed

    private void btnDivicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivicionActionPerformed
        valor1=Double.parseDouble(txtPantalla.getText());
        txtPantalla.setText("");
        operacion="divicion";
    }//GEN-LAST:event_btnDivicionActionPerformed

    private void btnPorcentajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPorcentajeActionPerformed
        valor1=Double.parseDouble(txtPantalla.getText());
        valor1 = valor1/100;
        txtPantalla.setText("");
        operacion="porcentaje";
    }//GEN-LAST:event_btnPorcentajeActionPerformed

    private void btnPuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPuntoActionPerformed
        
    }//GEN-LAST:event_btnPuntoActionPerformed

    private void rbBinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbBinarioActionPerformed
        rbOctal.setSelected(false);
        rbHexadecimal.setSelected(false);
        int n = Integer.parseInt(txtPantalla.getText());
        txtPantalla.setText(Long.toBinaryString(n));
    }//GEN-LAST:event_rbBinarioActionPerformed

    private void rbHexadecimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbHexadecimalActionPerformed
       rbOctal.setSelected(false);
        rbHexadecimal.setSelected(false);
        int n = Integer.parseInt(txtPantalla.getText());
        txtPantalla.setText(Long.toHexString(n));
    }//GEN-LAST:event_rbHexadecimalActionPerformed

    private void rbOctalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbOctalActionPerformed
        rbOctal.setSelected(false);
        rbHexadecimal.setSelected(false);
        int n = Integer.parseInt(txtPantalla.getText());
        txtPantalla.setText(Long.toOctalString(n));
    }//GEN-LAST:event_rbOctalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAutor;
    private javax.swing.JButton btnC;
    private javax.swing.JButton btnCe;
    private javax.swing.JButton btnCero;
    private javax.swing.JButton btnCinco;
    private javax.swing.JButton btnCoseno;
    private javax.swing.JButton btnCuatro;
    private javax.swing.JButton btnDivicion;
    private javax.swing.JButton btnDos;
    private javax.swing.JButton btnIn;
    private javax.swing.JButton btnLog;
    private javax.swing.JButton btnMas;
    private javax.swing.JButton btnMenos;
    private javax.swing.JButton btnMultiplicacion;
    private javax.swing.JButton btnNueve;
    private javax.swing.JButton btnOcho;
    private javax.swing.JButton btnPorcentaje;
    private javax.swing.JButton btnPunto;
    private javax.swing.JButton btnSeis;
    private javax.swing.JButton btnSeno;
    private javax.swing.JButton btnSiete;
    private javax.swing.JButton btnTangente;
    private javax.swing.JButton btnTres;
    private javax.swing.JButton btnUno;
    private javax.swing.JButton btnX;
    private javax.swing.JButton btnX2;
    private javax.swing.JButton btnXy;
    private javax.swing.JButton btnraizcuadrada;
    private javax.swing.JButton btnsignoX;
    private javax.swing.JButton jButtonResultados;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbBinario;
    private javax.swing.JRadioButton rbHexadecimal;
    private javax.swing.JRadioButton rbOctal;
    private javax.swing.JTextArea txtPantalla;
    // End of variables declaration//GEN-END:variables
}
